name: admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  file_picker: ^8.1.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  supabase_flutter: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
   
   
